plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // included dependencies
    include "com.electronwill.night-config:core:${night_config_version}"
    include implementation("com.electronwill.night-config:toml:${night_config_version}")

    include implementation("be.florens:expandability-fabric:${expandability_version}")

    // optional dependencies
    implementation "eu.pb4:trinkets:${trinkets_version}"

    implementation "me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}"

    implementation("com.terraformersmc:modmenu:${mod_menu_version}") { transitive = false }

    // compat & integration
    compileOnly "maven.modrinth:lootr:s0EnSZFB"
    compileOnly "io.github.apace100:apoli:${apoli_version}"
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
