org.gradle.jvmargs=-Xmx4096M

minecraft_version=1.21.11
enabled_platforms=fabric,neoforge

mod_id=artifacts
archives_name=artifacts
maven_group=artifacts
mod_version=14.0.1

# mod loaders
fabric_loader_version=0.18.2
fabric_api_version=0.141.2+1.21.11

neoforge_version=21.11.37-beta

# dependencies
expandability_version=13.0.0
curios_version=14.0.0+1.21.11

trinkets_version=3.11.0-beta.1+1.21.11
cardinal_components_version=7.3.0

accessories_version=1.3.8-beta+1.21.8
cloth_config_version=21.11.153
mod_menu_version=17.0.0-beta.2
curious_armor_stands_version=8.0.0

night_config_version=3.8.0

# compat
owo_version=0.12.15.4+1.21
lootr_version=1.21.11-1.19.33.100
apoli_version=2.12.0-alpha.15+mc.1.21.1
