# Reminder:
#   Check upstream multiloader template for changes if needed, and update
#   Gradle wrapper BEFORE changing the buildscript to prevent a potential headache.
#   ./gradlew wrapper --gradle-version <version>

# Project
version=15.1.3
group=artifacts
java_version=25

# Common
minecraft_version=26.2
mod_name=Artifacts
mod_author=Wouter
mod_id=artifacts
license=MIT
description=Adds various new powerful uncraftable items to make exploration a bit more rewarding
homepage=https://www.curseforge.com/minecraft/mc-mods/artifacts
sources=https://github.com/ochotonida/artifacts
issue_tracker=https://github.com/ochotonida/artifacts/issues
minecraft_version_range_fabric=~26.2
minecraft_version_range_neoforge=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.161.0+26.2
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.88
neoforge_version_range=[26.2.0.88,)

# Dependencies
expandability_version=15.0.0
curios_version=16.0.0+26.2
trinkets_version=4.1.1+26.2

# TODO: consider 'temporarily' removing this until accessories updates
accessories_version=1.3.8-beta+1.21.8
owo_version=0.12.15.4+1.21

cloth_config_version=26.2.155
mod_menu_version=20.0.3

# should probably match the version NeoForge uses
night_config_version=3.8.0

# Compat
lootr_version=26.2-1.24.41.123
# TODO: update when origins 26.1+ releases
apoli_version=2.12.0-alpha.15+mc.1.21.1

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
