org.gradle.jvmargs=-Xmx4096M

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

mod_id=artifacts
archives_name=artifacts
maven_group=artifacts
mod_version=13.2.3

fabric_loader_version=0.16.5
fabric_api_version=0.115.2+1.21.1

neoforge_version=21.1.211

expandability_version=12.0.0
curios_version=9.3.1+1.21.1
cloth_config_version=15.0.127
trinkets_version=3.10.0
mod_menu_version=11.0.0
cardinal_components_version=6.1.0
curious_armor_stands_version=8.0.0
accessories_version=1.1.0-beta.31+1.21.1
owo_version=0.12.15.4+1.21
lootr_version=1.21-1.10.35.90

night_config_version=3.8.0
