plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    accessTransformers.from(file('src/main/resources/META-INF/accesstransformer.cfg').absolutePath)
}

dependencies {
    // fabric (used by accessories (and maybe some other deps))
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // mixin
    compileOnly "org.ow2.asm:asm:9.7"
    compileOnly "org.ow2.asm:asm-tree:9.7"
    implementation "org.spongepowered:mixin:0.8.7"
    compileOnly "io.github.llamalad7:mixinextras-common:0.5.3"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.3"

    // required dependencies
    compileOnly "be.florens:expandability-fabric:${expandability_version}"
    compileOnly "com.electronwill.night-config:toml:${night_config_version}"

    // optional dependencies
    compileOnly("io.wispforest:accessories-common:${accessories_version}") {
        exclude(group: 'net.fabricmc.fabric-api')
    }

    compileOnly "eu.pb4:trinkets:${trinkets_version}"

    compileOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: 'net.fabricmc.fabric-api')
    }

    // compat & integration
    compileOnly "maven.modrinth:lootr:s0EnSZFB"
    compileOnly "maven.modrinth:origins:5o5sFcLS"
    compileOnly "io.github.apace100:apoli:${apoli_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets.main.resources.srcDirs = ['src/main/resources', 'src/generated/resources']

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.files
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
