modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
bannerFile="assets/artifacts/banner.png"
iconFile="assets/artifacts/icon.png"
logoBlur=false
authors="${mod_author}"
description='''${description}'''

[[mixins]]
config="${mod_id}.common.mixins.json"
[[mixins]]
config="${mod_id}.neoforge.mixins.json"

[[dependencies.artifacts]]
modId="neoforge"
type="required"
versionRange = "${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.artifacts]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.artifacts]]
modId = "curios"
type="optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.artifacts]]
modId = "trinkets_updated"
type="optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.artifacts]]
modId = "cloth_config"
type="optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
