plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

dependencies {
    // included dependencies (neoforge already includes night config)
    jarJar implementation("be.florens:expandability-neoforge:${expandability_version}")

    // optional dependencies
    implementation "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    implementation "eu.pb4:trinkets:${trinkets_version}"

    compileOnly "io.wispforest:accessories-neoforge:${accessories_version}"
    compileOnly "io.wispforest:owo-lib:${owo_version}"

    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"

    // compat & integration
    compileOnly "maven.modrinth:lootr:s0EnSZFB"
    compileOnly "io.github.apace100:apoli:${apoli_version}"
}

neoForge {
    version = neoforge_version
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file("runs/data"))
            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', findProject(':common').file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
